/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js;

import com.faug.mvc.js.FaugStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FaugStandaloneSetup extends FaugStandaloneSetupGenerated {
  public static void doSetup() {
    new FaugStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
