/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js;

import com.faug.mvc.js.AbstractFaugRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FaugRuntimeModule extends AbstractFaugRuntimeModule {
}
