/*
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class FaugProposalProvider extends AbstractFaugProposalProvider {
}
