/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.validation;

import com.faug.mvc.js.validation.AbstractFaugValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class FaugValidator extends AbstractFaugValidator {
}
