/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.json;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JSON Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.faug.mvc.js.json.JSONObject#getPairs <em>Pairs</em>}</li>
 * </ul>
 *
 * @see com.faug.mvc.js.json.JsonPackage#getJSONObject()
 * @model
 * @generated
 */
public interface JSONObject extends EObject
{
  /**
   * Returns the value of the '<em><b>Pairs</b></em>' containment reference list.
   * The list contents are of type {@link com.faug.mvc.js.json.JSONPair}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pairs</em>' containment reference list.
   * @see com.faug.mvc.js.json.JsonPackage#getJSONObject_Pairs()
   * @model containment="true"
   * @generated
   */
  EList<JSONPair> getPairs();

} // JSONObject
