/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.json;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JSON Array</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.faug.mvc.js.json.JSONArray#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see com.faug.mvc.js.json.JsonPackage#getJSONArray()
 * @model
 * @generated
 */
public interface JSONArray extends EObject
{
  /**
   * Returns the value of the '<em><b>Values</b></em>' containment reference list.
   * The list contents are of type {@link com.faug.mvc.js.json.JSONValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' containment reference list.
   * @see com.faug.mvc.js.json.JsonPackage#getJSONArray_Values()
   * @model containment="true"
   * @generated
   */
  EList<JSONValue> getValues();

} // JSONArray
