/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.json;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.faug.mvc.js.json.JsonPackage
 * @generated
 */
public interface JsonFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JsonFactory eINSTANCE = com.faug.mvc.js.json.impl.JsonFactoryImpl.init();

  /**
   * Returns a new object of class '<em>JSON Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>JSON Value</em>'.
   * @generated
   */
  JSONValue createJSONValue();

  /**
   * Returns a new object of class '<em>JSON Object</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>JSON Object</em>'.
   * @generated
   */
  JSONObject createJSONObject();

  /**
   * Returns a new object of class '<em>JSON Pair</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>JSON Pair</em>'.
   * @generated
   */
  JSONPair createJSONPair();

  /**
   * Returns a new object of class '<em>JSON Array</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>JSON Array</em>'.
   * @generated
   */
  JSONArray createJSONArray();

  /**
   * Returns a new object of class '<em>JSON String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>JSON String</em>'.
   * @generated
   */
  JSONString createJSONString();

  /**
   * Returns a new object of class '<em>JSON Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>JSON Number</em>'.
   * @generated
   */
  JSONNumber createJSONNumber();

  /**
   * Returns a new object of class '<em>JSON Boolean</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>JSON Boolean</em>'.
   * @generated
   */
  JSONBoolean createJSONBoolean();

  /**
   * Returns a new object of class '<em>JSON Null</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>JSON Null</em>'.
   * @generated
   */
  JSONNull createJSONNull();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  JsonPackage getJsonPackage();

} //JsonFactory
