/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.json;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JSON Pair</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.faug.mvc.js.json.JSONPair#getKey <em>Key</em>}</li>
 *   <li>{@link com.faug.mvc.js.json.JSONPair#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see com.faug.mvc.js.json.JsonPackage#getJSONPair()
 * @model
 * @generated
 */
public interface JSONPair extends EObject
{
  /**
   * Returns the value of the '<em><b>Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' containment reference.
   * @see #setKey(JSONString)
   * @see com.faug.mvc.js.json.JsonPackage#getJSONPair_Key()
   * @model containment="true"
   * @generated
   */
  JSONString getKey();

  /**
   * Sets the value of the '{@link com.faug.mvc.js.json.JSONPair#getKey <em>Key</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' containment reference.
   * @see #getKey()
   * @generated
   */
  void setKey(JSONString value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(JSONValue)
   * @see com.faug.mvc.js.json.JsonPackage#getJSONPair_Value()
   * @model containment="true"
   * @generated
   */
  JSONValue getValue();

  /**
   * Sets the value of the '{@link com.faug.mvc.js.json.JSONPair#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(JSONValue value);

} // JSONPair
