/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.json;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.faug.mvc.js.json.JsonFactory
 * @model kind="package"
 * @generated
 */
public interface JsonPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "json";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.json.org/";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "json";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JsonPackage eINSTANCE = com.faug.mvc.js.json.impl.JsonPackageImpl.init();

  /**
   * The meta object id for the '{@link com.faug.mvc.js.json.impl.JSONValueImpl <em>JSON Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.faug.mvc.js.json.impl.JSONValueImpl
   * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONValue()
   * @generated
   */
  int JSON_VALUE = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>JSON Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.faug.mvc.js.json.impl.JSONObjectImpl <em>JSON Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.faug.mvc.js.json.impl.JSONObjectImpl
   * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONObject()
   * @generated
   */
  int JSON_OBJECT = 1;

  /**
   * The feature id for the '<em><b>Pairs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_OBJECT__PAIRS = 0;

  /**
   * The number of structural features of the '<em>JSON Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_OBJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.faug.mvc.js.json.impl.JSONPairImpl <em>JSON Pair</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.faug.mvc.js.json.impl.JSONPairImpl
   * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONPair()
   * @generated
   */
  int JSON_PAIR = 2;

  /**
   * The feature id for the '<em><b>Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_PAIR__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_PAIR__VALUE = 1;

  /**
   * The number of structural features of the '<em>JSON Pair</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_PAIR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.faug.mvc.js.json.impl.JSONArrayImpl <em>JSON Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.faug.mvc.js.json.impl.JSONArrayImpl
   * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONArray()
   * @generated
   */
  int JSON_ARRAY = 3;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_ARRAY__VALUES = 0;

  /**
   * The number of structural features of the '<em>JSON Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_ARRAY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.faug.mvc.js.json.impl.JSONStringImpl <em>JSON String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.faug.mvc.js.json.impl.JSONStringImpl
   * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONString()
   * @generated
   */
  int JSON_STRING = 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_STRING__VALUE = 0;

  /**
   * The number of structural features of the '<em>JSON String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_STRING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.faug.mvc.js.json.impl.JSONNumberImpl <em>JSON Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.faug.mvc.js.json.impl.JSONNumberImpl
   * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONNumber()
   * @generated
   */
  int JSON_NUMBER = 5;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_NUMBER__VALUE = 0;

  /**
   * The number of structural features of the '<em>JSON Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_NUMBER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.faug.mvc.js.json.impl.JSONBooleanImpl <em>JSON Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.faug.mvc.js.json.impl.JSONBooleanImpl
   * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONBoolean()
   * @generated
   */
  int JSON_BOOLEAN = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_BOOLEAN__VALUE = 0;

  /**
   * The number of structural features of the '<em>JSON Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_BOOLEAN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.faug.mvc.js.json.impl.JSONNullImpl <em>JSON Null</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.faug.mvc.js.json.impl.JSONNullImpl
   * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONNull()
   * @generated
   */
  int JSON_NULL = 7;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_NULL__VALUE = 0;

  /**
   * The number of structural features of the '<em>JSON Null</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_NULL_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link com.faug.mvc.js.json.JSONValue <em>JSON Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Value</em>'.
   * @see com.faug.mvc.js.json.JSONValue
   * @generated
   */
  EClass getJSONValue();

  /**
   * Returns the meta object for the containment reference '{@link com.faug.mvc.js.json.JSONValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see com.faug.mvc.js.json.JSONValue#getValue()
   * @see #getJSONValue()
   * @generated
   */
  EReference getJSONValue_Value();

  /**
   * Returns the meta object for class '{@link com.faug.mvc.js.json.JSONObject <em>JSON Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Object</em>'.
   * @see com.faug.mvc.js.json.JSONObject
   * @generated
   */
  EClass getJSONObject();

  /**
   * Returns the meta object for the containment reference list '{@link com.faug.mvc.js.json.JSONObject#getPairs <em>Pairs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pairs</em>'.
   * @see com.faug.mvc.js.json.JSONObject#getPairs()
   * @see #getJSONObject()
   * @generated
   */
  EReference getJSONObject_Pairs();

  /**
   * Returns the meta object for class '{@link com.faug.mvc.js.json.JSONPair <em>JSON Pair</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Pair</em>'.
   * @see com.faug.mvc.js.json.JSONPair
   * @generated
   */
  EClass getJSONPair();

  /**
   * Returns the meta object for the containment reference '{@link com.faug.mvc.js.json.JSONPair#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Key</em>'.
   * @see com.faug.mvc.js.json.JSONPair#getKey()
   * @see #getJSONPair()
   * @generated
   */
  EReference getJSONPair_Key();

  /**
   * Returns the meta object for the containment reference '{@link com.faug.mvc.js.json.JSONPair#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see com.faug.mvc.js.json.JSONPair#getValue()
   * @see #getJSONPair()
   * @generated
   */
  EReference getJSONPair_Value();

  /**
   * Returns the meta object for class '{@link com.faug.mvc.js.json.JSONArray <em>JSON Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Array</em>'.
   * @see com.faug.mvc.js.json.JSONArray
   * @generated
   */
  EClass getJSONArray();

  /**
   * Returns the meta object for the containment reference list '{@link com.faug.mvc.js.json.JSONArray#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see com.faug.mvc.js.json.JSONArray#getValues()
   * @see #getJSONArray()
   * @generated
   */
  EReference getJSONArray_Values();

  /**
   * Returns the meta object for class '{@link com.faug.mvc.js.json.JSONString <em>JSON String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON String</em>'.
   * @see com.faug.mvc.js.json.JSONString
   * @generated
   */
  EClass getJSONString();

  /**
   * Returns the meta object for the attribute '{@link com.faug.mvc.js.json.JSONString#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.faug.mvc.js.json.JSONString#getValue()
   * @see #getJSONString()
   * @generated
   */
  EAttribute getJSONString_Value();

  /**
   * Returns the meta object for class '{@link com.faug.mvc.js.json.JSONNumber <em>JSON Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Number</em>'.
   * @see com.faug.mvc.js.json.JSONNumber
   * @generated
   */
  EClass getJSONNumber();

  /**
   * Returns the meta object for the attribute '{@link com.faug.mvc.js.json.JSONNumber#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.faug.mvc.js.json.JSONNumber#getValue()
   * @see #getJSONNumber()
   * @generated
   */
  EAttribute getJSONNumber_Value();

  /**
   * Returns the meta object for class '{@link com.faug.mvc.js.json.JSONBoolean <em>JSON Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Boolean</em>'.
   * @see com.faug.mvc.js.json.JSONBoolean
   * @generated
   */
  EClass getJSONBoolean();

  /**
   * Returns the meta object for the attribute '{@link com.faug.mvc.js.json.JSONBoolean#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.faug.mvc.js.json.JSONBoolean#getValue()
   * @see #getJSONBoolean()
   * @generated
   */
  EAttribute getJSONBoolean_Value();

  /**
   * Returns the meta object for class '{@link com.faug.mvc.js.json.JSONNull <em>JSON Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Null</em>'.
   * @see com.faug.mvc.js.json.JSONNull
   * @generated
   */
  EClass getJSONNull();

  /**
   * Returns the meta object for the attribute '{@link com.faug.mvc.js.json.JSONNull#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.faug.mvc.js.json.JSONNull#getValue()
   * @see #getJSONNull()
   * @generated
   */
  EAttribute getJSONNull_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JsonFactory getJsonFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.faug.mvc.js.json.impl.JSONValueImpl <em>JSON Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.faug.mvc.js.json.impl.JSONValueImpl
     * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONValue()
     * @generated
     */
    EClass JSON_VALUE = eINSTANCE.getJSONValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_VALUE__VALUE = eINSTANCE.getJSONValue_Value();

    /**
     * The meta object literal for the '{@link com.faug.mvc.js.json.impl.JSONObjectImpl <em>JSON Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.faug.mvc.js.json.impl.JSONObjectImpl
     * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONObject()
     * @generated
     */
    EClass JSON_OBJECT = eINSTANCE.getJSONObject();

    /**
     * The meta object literal for the '<em><b>Pairs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_OBJECT__PAIRS = eINSTANCE.getJSONObject_Pairs();

    /**
     * The meta object literal for the '{@link com.faug.mvc.js.json.impl.JSONPairImpl <em>JSON Pair</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.faug.mvc.js.json.impl.JSONPairImpl
     * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONPair()
     * @generated
     */
    EClass JSON_PAIR = eINSTANCE.getJSONPair();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_PAIR__KEY = eINSTANCE.getJSONPair_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_PAIR__VALUE = eINSTANCE.getJSONPair_Value();

    /**
     * The meta object literal for the '{@link com.faug.mvc.js.json.impl.JSONArrayImpl <em>JSON Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.faug.mvc.js.json.impl.JSONArrayImpl
     * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONArray()
     * @generated
     */
    EClass JSON_ARRAY = eINSTANCE.getJSONArray();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_ARRAY__VALUES = eINSTANCE.getJSONArray_Values();

    /**
     * The meta object literal for the '{@link com.faug.mvc.js.json.impl.JSONStringImpl <em>JSON String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.faug.mvc.js.json.impl.JSONStringImpl
     * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONString()
     * @generated
     */
    EClass JSON_STRING = eINSTANCE.getJSONString();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_STRING__VALUE = eINSTANCE.getJSONString_Value();

    /**
     * The meta object literal for the '{@link com.faug.mvc.js.json.impl.JSONNumberImpl <em>JSON Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.faug.mvc.js.json.impl.JSONNumberImpl
     * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONNumber()
     * @generated
     */
    EClass JSON_NUMBER = eINSTANCE.getJSONNumber();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_NUMBER__VALUE = eINSTANCE.getJSONNumber_Value();

    /**
     * The meta object literal for the '{@link com.faug.mvc.js.json.impl.JSONBooleanImpl <em>JSON Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.faug.mvc.js.json.impl.JSONBooleanImpl
     * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONBoolean()
     * @generated
     */
    EClass JSON_BOOLEAN = eINSTANCE.getJSONBoolean();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_BOOLEAN__VALUE = eINSTANCE.getJSONBoolean_Value();

    /**
     * The meta object literal for the '{@link com.faug.mvc.js.json.impl.JSONNullImpl <em>JSON Null</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.faug.mvc.js.json.impl.JSONNullImpl
     * @see com.faug.mvc.js.json.impl.JsonPackageImpl#getJSONNull()
     * @generated
     */
    EClass JSON_NULL = eINSTANCE.getJSONNull();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_NULL__VALUE = eINSTANCE.getJSONNull_Value();

  }

} //JsonPackage
