/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.ui.contentassist;

import com.faug.mvc.js.ui.contentassist.AbstractFaugProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class FaugProposalProvider extends AbstractFaugProposalProvider {
}
