/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.json.util;

import com.faug.mvc.js.json.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see com.faug.mvc.js.json.JsonPackage
 * @generated
 */
public class JsonAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static JsonPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JsonAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = JsonPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JsonSwitch<Adapter> modelSwitch =
    new JsonSwitch<Adapter>()
    {
      @Override
      public Adapter caseJSONValue(JSONValue object)
      {
        return createJSONValueAdapter();
      }
      @Override
      public Adapter caseJSONObject(JSONObject object)
      {
        return createJSONObjectAdapter();
      }
      @Override
      public Adapter caseJSONPair(JSONPair object)
      {
        return createJSONPairAdapter();
      }
      @Override
      public Adapter caseJSONArray(JSONArray object)
      {
        return createJSONArrayAdapter();
      }
      @Override
      public Adapter caseJSONString(JSONString object)
      {
        return createJSONStringAdapter();
      }
      @Override
      public Adapter caseJSONNumber(JSONNumber object)
      {
        return createJSONNumberAdapter();
      }
      @Override
      public Adapter caseJSONBoolean(JSONBoolean object)
      {
        return createJSONBooleanAdapter();
      }
      @Override
      public Adapter caseJSONNull(JSONNull object)
      {
        return createJSONNullAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link com.faug.mvc.js.json.JSONValue <em>JSON Value</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.faug.mvc.js.json.JSONValue
   * @generated
   */
  public Adapter createJSONValueAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.faug.mvc.js.json.JSONObject <em>JSON Object</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.faug.mvc.js.json.JSONObject
   * @generated
   */
  public Adapter createJSONObjectAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.faug.mvc.js.json.JSONPair <em>JSON Pair</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.faug.mvc.js.json.JSONPair
   * @generated
   */
  public Adapter createJSONPairAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.faug.mvc.js.json.JSONArray <em>JSON Array</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.faug.mvc.js.json.JSONArray
   * @generated
   */
  public Adapter createJSONArrayAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.faug.mvc.js.json.JSONString <em>JSON String</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.faug.mvc.js.json.JSONString
   * @generated
   */
  public Adapter createJSONStringAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.faug.mvc.js.json.JSONNumber <em>JSON Number</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.faug.mvc.js.json.JSONNumber
   * @generated
   */
  public Adapter createJSONNumberAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.faug.mvc.js.json.JSONBoolean <em>JSON Boolean</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.faug.mvc.js.json.JSONBoolean
   * @generated
   */
  public Adapter createJSONBooleanAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.faug.mvc.js.json.JSONNull <em>JSON Null</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.faug.mvc.js.json.JSONNull
   * @generated
   */
  public Adapter createJSONNullAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //JsonAdapterFactory
