/*
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FaugStandaloneSetup extends FaugStandaloneSetupGenerated {

	def static void doSetup() {
		new FaugStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
