/*
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FaugRuntimeModule extends AbstractFaugRuntimeModule {
}
