/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.ide;

import com.faug.mvc.js.FaugRuntimeModule;
import com.faug.mvc.js.FaugStandaloneSetup;
import com.faug.mvc.js.ide.FaugIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class FaugIdeSetup extends FaugStandaloneSetup {
  @Override
  public Injector createInjector() {
    FaugRuntimeModule _faugRuntimeModule = new FaugRuntimeModule();
    FaugIdeModule _faugIdeModule = new FaugIdeModule();
    return Guice.createInjector(Modules2.mixin(_faugRuntimeModule, _faugIdeModule));
  }
}
