/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.ide;

import com.faug.mvc.js.ide.AbstractFaugIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class FaugIdeModule extends AbstractFaugIdeModule {
}
