/*
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFaugScopeProvider extends DelegatingScopeProvider {
}
