/*
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FaugAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/faug/mvc/js/parser/antlr/internal/InternalFaug.tokens");
	}
}
