/**
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.ui;

import com.faug.mvc.js.ui.AbstractFaugUiModule;
import com.faug.mvc.js.ui.JsonUiIHyperlinkDetector;
import com.faug.mvc.js.ui.JsonUiIXtextEditorCallback;
import org.eclipse.jface.text.hyperlink.IHyperlinkDetector;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;
import org.eclipse.xtext.ui.resource.IResourceSetProvider;
import org.eclipse.xtext.ui.resource.SimpleResourceSetProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FaugUiModule extends AbstractFaugUiModule {
  @Override
  public Class<? extends IHyperlinkDetector> bindIHyperlinkDetector() {
    return JsonUiIHyperlinkDetector.class;
  }
  
  @Override
  public Class<? extends IXtextEditorCallback> bindIXtextEditorCallback() {
    return JsonUiIXtextEditorCallback.class;
  }
  
  @Override
  public Class<? extends IResourceSetProvider> bindIResourceSetProvider() {
    return SimpleResourceSetProvider.class;
  }
  
  public FaugUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
