/*
 * generated by Xtext 2.17.1
 */
package com.faug.mvc.js.ui;

import com.faug.mvc.js.ui.internal.JsActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FaugExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(JsActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		JsActivator activator = JsActivator.getInstance();
		return activator != null ? activator.getInjector(JsActivator.COM_FAUG_MVC_JS_FAUG) : null;
	}

}
